### ISSUE TITLE
implement `member.remove()` method in the MemberApi

### ISSUE THREAD

**Issue by achou11** [digidem/comapeo-core#258]
## Description

Extracted from #133 . Note that this is currently descoped for the MVP release.

## Tasks

- [x] assign role to BLOCKED
- [x] Allow blocked role to sync auth cores still
- [x] Test the role assignment propagates and the blocked user sees it
- [x] Test what happens if the removed member is disconnected when the remove happens and then reconnects (fix in separate PR if this is an issue)
- [x] Add event `project.on('own-role-update')` to listen for own role changing
- [x] Test new methods
